config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :allies, :except => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      post "add"
      post "remove"
    end
  end

  resources :medications

  resources :moods do
    collection do
      post "premade"
      post "quick_create"
    end
  end

  resources :categories do
    collection do
      post "premade"
      post "quick_create"
    end
  end

  resources :moments do
    collection do
      post "comment"
      post "quick_moment"
      get "delete_comment"
    end
  end

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post "comment"
      post "premade"
      post "quick_create"
      get "delete_comment"
    end
  end

  resources :groups do
    collection do
      get "join"
      get "leave"
    end
  end

  resources :meetings do
    collection do
      get "join"
      get "leave"
      post "comment"
      get "delete_comment"
    end
  end

  resources :profile, :except => [:show, :new, :create, :edit, :update, :destroy]

  resources :search, :except => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get "posts"
    end
  end

  resources :notifications, :except => [:show, :new, :create, :edit, :update] do
    collection do
      delete 'clear'
      get "fetch_notifications"
      get "signed_in"
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'contributors', to: 'pages#contributors', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'blog', to: 'pages#blog', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => 'omniauth_callbacks', :invitations => 'users/invitations' }

  mount Ckeditor::Engine => "/ckeditor"

  post 'pusher/auth'

  root "pages#home"
end

app/controllers/allies_controller.rb
# frozen_string_literal: true

class AlliesController < ApplicationController
  # GET /allies
  # GET /allies.json
  def index
    @page_search = true
    @accepted_allies = current_user.allies_by_status(:accepted)
                                   .sort_by! { |n| n.name.downcase }
    @incoming_ally_requests = current_user.allies_by_status(:pending_from_user)
                                          .sort_by! { |n| n.name.downcase }
    @outgoing_ally_requests = current_user.allies_by_status(:pending_from_ally)
                                          .sort_by! { |n| n.name.downcase }
  end

  def add
    ally_id = params[:ally_id]
    allyship = Allyship.find_by(
      user_id: current_user.id, ally_id: ally_id
    )

    if allyship
      allyship.update(status: User::ALLY_STATUS[:accepted])

      # Notify the user who made the request
      pusher_type = 'accepted_ally_request'

      # Get rid of original new_ally_request notification
      Notification.where(
        userid: current_user.id,
        uniqueid: "new_ally_request_#{ally_id}"
      ).destroy_all
    else
      Allyship.create(
        user_id: current_user.id,
        ally_id: ally_id,
        status: User::ALLY_STATUS[:pending_from_ally]
      )

      # Notify the user the request has been made to
      pusher_type = 'new_ally_request'
    end

    uniqueid = "#{pusher_type}_#{current_user.id}"
    data = JSON.generate(
      user: current_user.name,
      userid: current_user.id,
      uid: current_user.uid,
      type: pusher_type,
      uniqueid: uniqueid
    )

    Notification.create(
      userid: ally_id,
      uniqueid: uniqueid,
      data: data
    )

    notifications = Notification.where(userid: ally_id).order(:created_at)
    Pusher["private-#{ally_id}"]
      .trigger('new_notification', notifications: notifications)

    NotificationMailer.notification_email(ally_id, data).deliver_now

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  def remove
    user_id = current_user.id
    ally_id = params[:ally_id].to_i

    # Destroy allyship
    Allyship.where(user_id: user_id, ally_id: ally_id).destroy_all

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/views/allies/index.html.erb
<% title t('allies.index.title') %>
<div id="allies_search">
  <%= render :partial => '/search/form' %>
  <div class="small_margin_top">
  <%= link_to t('allies.index.invite'), new_user_invitation_path %>
  </div>
</div>

<% if !@outgoing_ally_requests.empty? %>
  <strong><%= t('allies.index.outgoing') %></strong>
  <br>
  <br>
  <div class="allies_list">
  <% @outgoing_ally_requests.each do |ally| %>
    <div class="ally center">
      <%= ProfilePicture.fetch(ally.avatar.url, 'profile_picture') %>
      <h1 class="ally_name"><%= link_to ally.name, profile_index_path(uid: get_uid(ally.id)) %></h1>
      <div class="location"><%= ally.location %></div>
      <%= link_to t('allies.index.cancel'), remove_allies_path(ally_id: ally.id), :method => :post, data: { confirm: t('common.actions.confirm') } %>
    </div>
  <% end %>
  </div>
<% end %>

<% if !@incoming_ally_requests.empty? %>
  <% if !@outgoing_ally_requests.empty? %>
    <div class="spacer"></div>
  <% end %>
  <strong><%= t('allies.index.incoming') %></strong>
  <br>
  <br>
  <div class="allies_list">
  <% @incoming_ally_requests.each do |ally| %>
    <div class="ally center">
      <%= ProfilePicture.fetch(ally.avatar.url, 'profile_picture') %>
      <h1 class="ally_name"><%= link_to ally.name, profile_index_path(uid: get_uid(ally.id)) %></h1>
      <div class="location"><%= ally.location %></div>
      <%= link_to t('allies.accept'), add_allies_path(ally_id: ally.id), method: :post %> | <%= link_to t('common.actions.remove'), remove_allies_path(ally_id: ally.id), :method => :post, data: { confirm: t('common.actions.confirm') } %>
    </div>
  <% end %>
  </div>
<% end %>

<% if @accepted_allies.present? %>
  <div class="spacer"></div>
  <strong><%= t('allies.index.title') %></strong>
  <br>
  <br>
<% end %>

<% if @accepted_allies.present? %>
<div class="allies_list">
<% @accepted_allies.each do |ally| %>
  <div class="ally center">
    <%= ProfilePicture.fetch(ally.avatar.url, 'profile_picture') %>
    <h1 class="ally_name"><%= link_to ally.name, profile_index_path(uid: get_uid(ally.id)) %></h1>
    <div class="location"><%= ally.location %></div>
    <%= link_to t('common.actions.remove'), remove_allies_path(ally_id: ally.id), :method => :post, data: { confirm: t('common.actions.confirm') } %>
  </div>
<% end %>
</div>
<% end %>

<% if @outgoing_ally_requests.empty? && @incoming_ally_requests.empty? && @accepted_allies.count == 0 %>
  <%= t('allies.index.none') %>
<% end %>