config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :allies, :except => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      post "add"
      post "remove"
    end
  end

  resources :medications

  resources :moods do
    collection do
      post "premade"
      post "quick_create"
    end
  end

  resources :categories do
    collection do
      post "premade"
      post "quick_create"
    end
  end

  resources :moments do
    collection do
      post "comment"
      post "quick_moment"
      get "delete_comment"
    end
  end

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post "comment"
      post "premade"
      post "quick_create"
      get "delete_comment"
    end
  end

  resources :groups do
    collection do
      get "join"
      get "leave"
    end
  end

  resources :meetings do
    collection do
      get "join"
      get "leave"
      post "comment"
      get "delete_comment"
    end
  end

  resources :profile, :except => [:show, :new, :create, :edit, :update, :destroy]

  resources :search, :except => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get "posts"
    end
  end

  resources :notifications, :except => [:show, :new, :create, :edit, :update] do
    collection do
      delete 'clear'
      get "fetch_notifications"
      get "signed_in"
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'contributors', to: 'pages#contributors', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'blog', to: 'pages#blog', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => 'omniauth_callbacks', :invitations => 'users/invitations' }

  mount Ckeditor::Engine => "/ckeditor"

  post 'pusher/auth'

  root "pages#home"
end

app/views/shared/_autocomplete_checkboxes.html.erb
<% f = local_assigns[:f] %>
<% all_data = local_assigns[:all_data] %>
<% this_data = local_assigns[:this_data] %>
<% data_type = local_assigns[:data_type] %>
<% data_type_plural = local_assigns[:data_type_plural] %>

<div class="sidebar_field">
  <div class="sidebar_label expand_toggle" data-toggle="<%= "##{data_type_plural}" %>">
    <a href="#" class="toggle_button">
      <i class="fa fa-caret-down"></i>
    </a>
    <%= f.label t("#{data_type_plural}.plural") %>
  </div>

  <div id="<%= data_type_plural %>" class="display_none">

    <% if all_data.present? %>
      <%= f.text_field "#{data_type}_name", data: { autocomplete_source: all_data.map(&:name), autocomplete_source_ids: all_data.map(&:id) }, class: 'full_field smaller_margin_top smaller_margin_bottom', placeholder: t('common.form.press_enter') %>
    <% end %>

    <div id="<%= "#{data_type_plural}_list" %>">
      <% if all_data.present? %>
        <% all_data.each do |item| %>
          <div id="<%= "#{data_type}_name_#{item.id}" %>" class="<%= this_data.include?(item.id) ? 'display_block' : 'display_none' %>"><%= f.check_box(data_type, { multiple: true, checked: this_data.include?(item.id) }, item.id, nil) %><span><%= item.name %></span><br></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_back_to_top.html.erb
<div class="back_to_top"><i class="fa fa-chevron-up smaller_margin_right"></i><%= t('back_to_top') %></div>

app/views/shared/_character_count.html.erb
<div class="character_count subtle">
	<%= raw t('shared.character_count', {
			number: content_tag(:span, '2000', id: local_assigns[:data].to_s + '_count')
		}) %>
</div>

app/views/shared/_editor_modal.html.erb
<div id="editor_modal" class="display_none">
  <div id="editor_text">
    <div class="titlebar">
      <div class="align_right">
          <h1 id="close_editor" class="align_right"><i class="fa fa-times"></i></h1>
          <div class="clear"></div>
      </div>
      <div class="clear"></div>
    </div>
    <div class="modal_text" id="modal_text">
      <%= cktext_area :modal, :editor, ckeditor: { display:'none', height:'70vh' }, class: 'no_title special_textarea ckeditor' %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div id="header_content">
    <div class="ifme-logo small-screen">
      <%= link_to root_path do %>
        <span class="logo-text header-logo">If <span class="me">Me</span></span>
      <% end %>

      <i class="expand fa fa-bars" id="expand_nav"></i>

      <ul id="small_nav" class="display_none">
      <% if user_signed_in? %>
          <%= nav_link_to(t('moments.plural'), moments_path) %>
          <%= nav_link_to(t('categories.plural'), categories_path) %>
          <%= nav_link_to(t('moods.plural'), moods_path) %>
          <%= nav_link_to(t('strategies.plural'), strategies_path) %>
          <%= nav_link_to(t('medications.index.title'), medications_path) %>
          <%= nav_link_to(t('groups.plural'), groups_path) %>
          <%= nav_link_to(t('allies.index.title'), allies_path) %>
          <div class="horizonal_divider"></div>
          <%= nav_link_to(t('notifications.plural'), "", class: 'notifications_button') %>
          <%= nav_link_to(t('profile.index.title'), profile_index_path(uid: current_user.uid)) %>
          <%= nav_link_to(t('account.singular'), edit_user_registration_path) %>
          <%= nav_link_to(t('navigation.resources'), resources_path) %>
          <%= nav_link_to(t('shared.header.signout'), destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= nav_link_to(t('account.sign_in'), new_user_session_path) %>
          <%= nav_link_to(t('common.actions.join'), new_user_registration_path) %>
          <div class="horizonal_divider"></div>
          <%= nav_link_to(t('navigation.about'), about_path) %>
          <%= nav_link_to(t('navigation.blog'), blog_path) %>
          <%= nav_link_to(t('navigation.resources'), resources_path) %>
        <% end %>
      </ul>
    </div>

    <div class="ifme-logo large-screen">
      <%= render "shared/menu_logo" %>

      <ul class="top-nav primary-nav">
        <% if user_signed_in? %>
          <%= nav_link_to(t('shared.header.home'), root_path)  %>
          <%= nav_link_to(t('moments.plural'), moments_path, :class => "expand_moment_button") %>
          <%= nav_link_to(t('strategies.plural'), strategies_path) %>
          <%= nav_link_to(t('medications.index.title'), medications_path) %>
          <%= nav_link_to(t('groups.plural'), groups_path) %>
          <%= nav_link_to(t('allies.index.title'), allies_path) %>
        <% else %>
          <%= nav_link_to(t('account.sign_in'), new_user_session_path) %>
          <%= nav_link_to(t('common.actions.join'), new_user_registration_path) %>
          <li><div class="vertical_divider"></div></li>
          <%= nav_link_to(t('navigation.about'), about_path) %>
          <%= nav_link_to(t('navigation.blog'), blog_path) %>
          <%= nav_link_to(t('navigation.resources'), resources_path) %>
        <% end %>
        <div class="clear"></div>
      </ul>

      <% if user_signed_in? %>
        <ul id="expand_moment" class="top-nav display_none">
          <%= nav_link_to(t('categories.plural'), categories_path) %>
          <%= nav_link_to(t('moods.plural'), moods_path) %>
        </ul>

        <ul id="expand_me" class="top-nav large-screen display_none">
          <%= nav_link_to(t('notifications.plural'), "", class: 'notifications_button') %>
          <%= nav_link_to(t('profile.index.title'), profile_index_path(uid: current_user.uid)) %>
          <%= nav_link_to(t('account.singular'), edit_user_registration_path) %>
          <%= nav_link_to(t('navigation.resources'), resources_path) %>
          <%= nav_link_to(t('shared.header.signout'), destroy_user_session_path, :method => :delete) %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_locale.html.erb
<%= select_tag "locale", options_for_select(@locales.collect{ |l| [l[:name], l[:locale]] }, @locale) %>

app/views/shared/_meeting_info.html.erb
<div class="small_margin_bottom">
  <%= raw(meeting.description) %>
</div>

<strong>
  <%= t('common.form.location') %>:
</strong>

<% if meeting.location.match(/^https?:\/\/|www\./) %>
  <%= link_to meeting.location, meeting.location %>
<% else %>
  <%= link_to meeting.location,
    "https://www.google.com/maps/place/" + meeting.location %>
<% end %>
<br>
<strong>
  <%= t('common.date') %>
</strong>
<%= meeting.date %>
<br>
<strong>
  <%= t('meetings.info.meeting_time') %>:
</strong>
<%= meeting.time %>

<div class="notification_wrapper">
  <strong class="tip_notifications_button">
    <i class="fa fa-list small_margin_right"></i>
    <% if local_assigns[:show_group] %>
      <%= t('meetings.info.members_of_group_html',
            count: meeting.members.count,
            group: link_to(meeting.group.name, meeting.group)) %>
    <% else %>
      <%= t('members', count: meeting.members.count) %>
    <% end %>
  </strong>

  <%= render partial: '/notifications/members', locals: { group: meeting } %>
</div>

<strong>
  <%= get_meeting_members(meeting) %>
</strong>

<% if meeting.leaders.include? current_user %>
  <br>
  <br>
  <i class="fa fa-trash-o action"></i>
  <%= link_to t('meetings.info.cancel_meeting'), meeting, method: :delete, data: { confirm: t('common.actions.confirm') } %>
<% end %>

app/views/shared/_modal.html.erb
<div class="titlebar">
  <div class="align_left">
    <h1 class="notification_name"><%= local_assigns[:modal_title] %></h1>
  </div>
  <div class="align_right">
    <% if local_assigns[:modal_clear] %>
      <% if Notification.all.size > 0 %>
        <h1 id="clear_notifications" class="align_left small_margin_right"><%= local_assigns[:modal_clear] %></h1>
      <% else %>
      <% end %>
      <h1 id="close_notifications" class="align_right"><i class="fa fa-times"></i></h1>
    <div class="clear"></div>
    <% elsif local_assigns[:modal_close_class] %>
      <h1 class=<%= "#{local_assigns[:modal_close_class].to_s} align_right" %>><i class="fa fa-times"></i></h1>
    <% elsif local_assigns[:modal_close_id] %>
      <h1 id=<%= local_assigns[:modal_close_id].to_s %> class="align_right"><i class="fa fa-times"></i></h1>
    <% end %>
  </div>
  <div class="clear"></div>
</div>

app/views/shared/_moments_strategies.html.erb
<% if local_assigns[:data_type] == 'moment' || local_assigns[:data_type] == 'moment_tag_usage' %>
    <div class="moment">
      <h1 class="moment_name">
        <%= render :partial => '/shared/viewers_hover', locals: { data: local_assigns[:item] } %>
        <%= link_to local_assigns[:item].name, local_assigns[:item] %>
      </h1>

      <%= render :partial => '/moments/info', locals: { data: local_assigns[:item], show_strategies: true } %>

      <% if current_user.id == local_assigns[:item].userid %>
      <div class="small_margin_top">
        <i class="fa fa-pencil action"></i><%= link_to t('common.actions.edit'), edit_moment_path(local_assigns[:item]) %>
        <% if local_assigns[:data_type] == 'moment' %>
        <i class="fa fa-trash-o action small_margin_left"></i><%= link_to t('common.actions.delete'), local_assigns[:item], method: :delete, data: { confirm: t('common.actions.confirm') } %>
        <% end %>
      </div>
      <% end %>
    </div>
<% elsif local_assigns[:data_type] == 'strategy' || local_assigns[:data_type] == 'strategy_tag_usage' %>
      <div class="strategy">
      <h1 class="strategy_name">
        <%= render :partial => '/shared/viewers_hover', locals: { data: local_assigns[:item] } %>
        <%= link_to local_assigns[:item].name, local_assigns[:item] %>
      </h1>
      <%= ::TimeAgo.created_or_edited(local_assigns[:item]) %>
      <% if local_assigns[:item].category.count > 0 %>
        <br>
        <strong>
          <%= t('categories.label', count: local_assigns[:item].category.count) %>
        </strong>
        <% local_assigns[:item].category.each do |item| %>
          <% if Category.where(id: item, userid: current_user.id).exists? %>
          <span class="notification_wrapper">
            <span class="tip_notifications_button link_style"><%= Category.where(id: item).first.name %></span><% if local_assigns[:item].category.last != item %><%= ', ' %><% end %>
            <%= render :partial => '/notifications/preview', locals: { data: Category.where(id: item).first, edit: edit_category_path(item) } %>
          </span>
          <% end %>
        <% end %>
      <% end %>
      <% if current_user.id == local_assigns[:item].userid %>
      <div class="small_margin_top">
        <i class="fa fa-pencil action"></i><%= link_to t('common.actions.edit'), edit_strategy_path(local_assigns[:item]) %>
        <% if local_assigns[:data_type] == 'strategy' %>
        <i class="fa fa-trash-o action small_margin_left"></i><%= link_to t('common.actions.delete'), local_assigns[:item], method: :delete, data: { confirm: t('common.actions.confirm') } %>
        <% end %>
      </div>
      <% end %>
    </div>
<% end %>

app/views/shared/_quick_create.html.erb
<div class="quick_create display_none" id=<%= "#{local_assigns[:data_type].to_s}_quick_create" %> >
	<div class="quick_create_text">
		<%= render :partial => '/shared/modal',
			locals: {
				modal_title: "#{t('shared.quick_create.new', name: local_assigns[:data_type].to_s.titleize)}",
				modal_close_class: 'quick_create_close',
			}
		%>

		<div class="modal_text">
		<%
			if local_assigns[:data_type] == 'category'
				url = quick_create_categories_path
			elsif local_assigns[:data_type] == 'mood'
				url = quick_create_moods_path
			elsif local_assigns[:data_type] == 'strategy'
				url = quick_create_strategies_path
			end
		%>

		<%= form_for(local_assigns[:data], url: url) do |f| %>
			<% if local_assigns[:data].errors.any? %>
			  	<div class="error_explanation">
			  	<% if local_assigns[:data_type] == 'category' %>
					<%= t('common.form.error_explanation') %>
			  	<% elsif local_assigns[:data_type] == 'mood' %>
					<%= t('common.form.error_explanation') %>
			  	<% elsif local_assigns[:data_type] == 'strategy' %>
					<%= t('common.form.error_explanation') %>
			  	<% end %>
			  	</div>
			<% end %>

			<%= render :partial => '/shared/quick_create_fields', locals: { data_type: local_assigns[:data_type], f: f } %>

			<div class="clear"></div>

			<div class="actions no_margin_bottom">
				<%= f.hidden_field :tag, :value => local_assigns[:tag] %>
				<%= f.hidden_field :data_type, :value => local_assigns[:data_type] %>
				<%= f.hidden_field :userid, :value => current_user.id %>
				<%= f.submit t('common.actions.add') %>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/shared/_quick_create_fields.html.erb
<% if local_assigns[:data_type] == 'category' %>

<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('common.name') %>
		<i class="fa fa-asterisk align_right"></i>
		<div class="clear"></div>
	</div>
	<%= local_assigns[:f].text_field :name, :class => "name_field" %>
</div>

<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('common.form.description') %>
	</div>
	<%= local_assigns[:f].text_area :description, class: 'no_title' %>
</div>

<% elsif local_assigns[:data_type] == 'mood' %>

<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('common.name') %>
		<i class="fa fa-asterisk align_right"></i>
		<div class="clear"></div>
	</div>
	<%= local_assigns[:f].text_field :name, :class => "name_field" %>
</div>

<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('common.form.description') %>
	</div>
	<%= local_assigns[:f].text_area :description, class: 'no_title' %>
</div>

<% elsif local_assigns[:data_type] == 'strategy' %>

<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('common.title') %>
		<i class="fa fa-asterisk align_right"></i>
		<div class="clear"></div>
	</div>
	<%= local_assigns[:f].text_field :name, :class => "name_field" %>
</div>

<% categories = Category.where(userid: current_user.id).all %>
<% if !categories.nil? && categories.length > 0 %>
<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('categories.plural') %>
	</div>
	<% categories.each do |item| %>
		<%= local_assigns[:f].check_box(:category, {:multiple => true, :checked => @strategy.category.include?(item.id)}, item.id, nil) %><%= item.name %><br>
	<% end %>
</div>
<% end %>

<div class="field">
	<div class="label">
		<%= local_assigns[:f].label t('strategies.form.describe') %>
		<i class="fa fa-asterisk align_right"></i>
		<div class="clear"></div>
	</div>
	<%= local_assigns[:f].text_area :description, class: 'no_title' %>
	<%= render :partial => '/shared/character_count', locals: { data: 'strategy_description' } %>
</div>

<% end %>

app/views/shared/_stats.html.erb
<% if local_assigns[:data_type] == 'category' || local_assigns[:data_type] == 'mood' || local_assigns[:data_type] == 'strategy' %>
	<% most_focus = most_focus(local_assigns[:data_type], local_assigns[:profile]) %>
	<% if most_focus.length > 0 %>

		<% if !local_assigns[:profile] %>
			<div class="stats_divider"></div>
		<% end %>

	<div class="center" id="stats">
		<% if local_assigns[:profile] %>
		<div class="main_message no_margin_top">
			<%= local_assigns[:data_type].pluralize.titleize %>
		</div>
		<% end %>
		<div class="small_margin_bottom">
			<% if !local_assigns[:profile] || local_assigns[:profile] == current_user.id %>
				<%= t('shared.stats.you_are_focusing') %>
			<% elsif local_assigns[:profile] %>
				<%= t('shared.stats.user_is_focusing', name: User.where(id: local_assigns[:profile]).first.name) %>
			<% end %>
		</div>

		<div id="most_focus">
			<% most_focus.each do |key, value| %>
				
				<div class="some_focus">
				
					<div class="some_focus_text">
					<% if local_assigns[:data_type] == 'category' && (!local_assigns[:profile] || local_assigns[:profile] == current_user.id) %>
						<%= viewers_hover(get_viewers_for(Category.where(id: key).first, 'category'), Category.where(id: key).first) %>
					<% elsif local_assigns[:data_type] == 'category' && local_assigns[:profile] %>
						<%= Category.where(id: key).first.name %>
					<% elsif local_assigns[:data_type] == 'mood' && (!local_assigns[:profile] || local_assigns[:profile] == current_user.id) %>
						<%= viewers_hover(get_viewers_for(Mood.where(id: key).first, 'mood'), Mood.where(id: key).first) %>
					<% elsif local_assigns[:data_type] == 'mood' && local_assigns[:profile] %>
						<%= Mood.where(id: key).first.name %>
					<% elsif local_assigns[:data_type] == 'strategy' && (!local_assigns[:profile] || local_assigns[:profile] == current_user.id) %>
						<%= viewers_hover(get_viewers_for(Strategy.where(id: key).first, 'strategy'), Strategy.where(id: key).first) %>
					<% elsif local_assigns[:data_type] == 'strategy' && local_assigns[:profile] %>
						<%= Strategy.where(id: key).first.name %>
					<% end %>
					</div>
				</div>
			<% end %>
		</div>

		<div class="clear"></div>
	</div>
	<% end %>
<% elsif local_assigns[:data_type] == 'moment' %>
	<%= raw(moments_stats) %>
<% end %>

app/views/shared/_tag_usage.html.erb
<% if local_assigns[:data_type] == 'category' || local_assigns[:data_type] == 'mood' || local_assigns[:data_type] == 'strategy' %>

    <div id="tag_usage" class="small_margin_top">

    <% usage = tag_usage(local_assigns[:data], local_assigns[:data_type], local_assigns[:userid]) %>

    <% if local_assigns[:data_type] == 'category' %>
        <% moments = usage[0] %>
        <% strategies = usage[1] %>

        <% if moments.length > 0 %>
        <h1 class="tag_type"><%= t('moments.tagged') %></h1>

        <div id="moment_tag_usage">
      <div class="tag_usage">
        <% moments.each do |moment_id| %>
            <% moment = Moment.where(id: moment_id).first %>
            <% if moment.userid == current_user.id || moment.viewers.include?(current_user.id) %>
            <%= render :partial => '/shared/moments_strategies', locals: { items: moments, item: moment, data_type: 'moment_tag_usage' } %>
            <% end %>
        <% end %>
        </div>
    </div>
    <% end %>

    <% if strategies.length > 0 %>
        <h1 class="tag_type margin_top"><%= t('strategies.plural') %></h1>

        <div id="strategy_tag_usage">
      <div class="tag_usage">
        <% strategies.each do |strategy_id| %>
            <% strategy = Strategy.where(id: strategy_id).first %>
            <% if strategy.userid == current_user.id || strategy.viewers.include?(current_user.id) %>
            <%= render :partial => '/shared/moments_strategies', locals: { items: strategies, item: strategy, data_type: 'strategy_tag_usage' } %>
            <% end %>
        <% end %>
        </div>
    </div>
    <% end %>
    <% else %>
        <% moments = usage %>

        <% if moments.length > 0 %>
            <% if local_assigns[:data_type] == 'strategy' %>
                <h1 class="tag_type">
                    <%= t('moments.tagged') %>
                    <span id="showTaggedMoments" class="align_right display_inline_block"><i class="fa fa-caret-down"></i></span>
                    <span id="hideTaggedMoments" class="align_right display_none"><i class="fa fa-caret-up"></i></span>
                </h1>

                <div id="moment_tag_usage" class="display_none">
        <div class="tag_usage">
            <% else %>
                <h1 class="tag_type"><%= t('moments.tagged') %></h1>
                <div id="moment_tag_usage">
        <div class="tag_usage">
            <% end %>

            <% moments.each do |moment_id| %>
                <% moment = Moment.where(id: moment_id).first %>
                <% if moment.userid == current_user.id || moment.viewers.include?(current_user.id) %>
                <%= render :partial => '/shared/moments_strategies', locals: { items: moments, item: moment, data_type: 'moment_tag_usage' } %>
                <% end %>
            <% end %>
            </div>
      </div>
        <% end %>
    <% end %>
</div>
<% end %>

app/views/shared/_viewers_hover.html.erb
<% if local_assigns[:data].userid == current_user.id %>
	<%= viewers_hover(local_assigns[:data].viewers, nil) %>
<% end %>