config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'

  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  resources :allies, :except => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      post "add"
      post "remove"
    end
  end

  resources :medications

  resources :moods do
    collection do
      post "premade"
      post "quick_create"
    end
  end

  resources :categories do
    collection do
      post "premade"
      post "quick_create"
    end
  end

  resources :moments do
    collection do
      post "comment"
      post "quick_moment"
      get "delete_comment"
    end
  end

  resources :secret_shares, only: [:create, :show, :destroy]

  resources :strategies do
    collection do
      post "comment"
      post "premade"
      post "quick_create"
      get "delete_comment"
    end
  end

  resources :groups do
    collection do
      get "join"
      get "leave"
    end
  end

  resources :meetings do
    collection do
      get "join"
      get "leave"
      post "comment"
      get "delete_comment"
    end
  end

  resources :profile, :except => [:show, :new, :create, :edit, :update, :destroy]

  resources :search, :except => [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get "posts"
    end
  end

  resources :notifications, :except => [:show, :new, :create, :edit, :update] do
    collection do
      delete 'clear'
      get "fetch_notifications"
      get "signed_in"
    end
  end

  get 'pages/home'
  match 'about', to: 'pages#about', via: :get
  match 'contributors', to: 'pages#contributors', via: :get
  match 'partners', to: 'pages#partners', via: :get
  match 'blog', to: 'pages#blog', via: :get
  match 'privacy', to: 'pages#privacy', via: :get
  match 'faq', to: 'pages#faq', via: :get
  match 'toggle_locale', to: 'pages#toggle_locale', via: :get
  match 'press', to: 'pages#press', via: :get
  match 'resources', to: 'pages#resources', via: :get

  devise_for :users, :controllers => { :registrations => :registrations, :omniauth_callbacks => 'omniauth_callbacks', :invitations => 'users/invitations' }

  mount Ckeditor::Engine => "/ckeditor"

  post 'pusher/auth'

  root "pages#home"
end

app/models/moment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: moments
#
#  id         :integer          not null, primary key
#  category   :text
#  name       :string
#  mood       :text
#  why        :text
#  fix        :text
#  created_at :datetime
#  updated_at :datetime
#  userid     :integer
#  viewers    :text
#  comment    :boolean
#  strategy   :text
#  slug       :string
#

class Moment < ApplicationRecord
  include Viewer
  extend FriendlyId

  friendly_id :name
  serialize :category, Array
  serialize :viewers, Array
  serialize :mood, Array
  serialize :strategy, Array

  before_save :array_data

  belongs_to :user, foreign_key: :userid
  has_many :comments, as: :commentable

  validates :comment, inclusion: [true, false]
  validates :userid, :name, :why, presence: true
  validates :why, length: { minimum: 1, maximum: 2000 }
  validates :fix, length: { maximum: 2000 }
  validates :secret_share_expires_at,
            presence: true, if: :secret_share_identifier?

  def self.find_secret_share!(identifier)
    find_by!(
      'secret_share_expires_at > NOW()',
      secret_share_identifier: identifier
    )
  end

  def array_data
    self.category = category.collect(&:to_i) if category.is_a?(Array)
    self.viewers = viewers.collect(&:to_i) if viewers.is_a?(Array)
    self.mood = mood.collect(&:to_i) if mood.is_a?(Array)
    self.strategy = strategy.collect(&:to_i) if strategy.is_a?(Array)
  end

  def category_name
    category.try(:name)
  end

  def mood_name
    mood.try(:name)
  end

  def strategy_name
    strategy.try(:name)
  end

  def owned_by?(user)
    user&.id == userid
  end

  def shared?
    secret_share_identifier? &&
      Time.zone.now < secret_share_expires_at
  end
end

app/controllers/moments_controller.rb
# frozen_string_literal: true

class MomentsController < ApplicationController
  include CollectionPageSetup

  before_action :set_moment, only: %i[show edit update destroy]

  # GET /moments
  # GET /moments.json
  def index
    if current_user
      @user_logged_in = true

      period = 'day'
      # +1 day buffer to ensure we include today as well
      end_date = Date.current + 1.day
      start_date = get_start_by_period(period, end_date)

      @react_moments = Moment.where(user: current_user)
                             .group_by_period(period,
                                              :created_at,
                                              range: start_date..end_date).count
    else
      @user_logged_in = false
    end

    page_collection('@moments', 'moment')
  end

  # GET /moments/1
  # GET /moments/1.json
  def show
    show_with_comments(@moment)
  end

  def comment
    comment_for('moment')
  end

  def delete_comment
    comment_exists = Comment.where(id: params[:commentid]).exists?
    is_my_comment = Comment.where(id: params[:commentid], comment_by: current_user.id).exists?

    if comment_exists
      momentid = Comment.where(id: params[:commentid]).first.commentable_id
      is_my_moment = Moment.where(id: momentid, userid: current_user.id).exists?
      is_a_viewer = is_viewer(Moment.where(id: momentid).first.viewers)
    else
      is_my_moment = false
      is_a_viewer = false
    end

    if comment_exists && ((is_my_comment && is_a_viewer) || is_my_moment)
      Comment.find(params[:commentid]).destroy

      # Delete corresponding notifications
      public_uniqueid = 'comment_on_moment_' + params[:commentid].to_s
      Notification.where(uniqueid: public_uniqueid).destroy_all

      private_uniqueid = 'comment_on_moment_private_' + params[:commentid].to_s
      Notification.where(uniqueid: private_uniqueid).destroy_all
    end

    head :ok
  end

  def quick_moment
    # Assumme all viewers and comments allowed
    viewers = []
    current_user.allies_by_status(:accepted).each do |item|
      viewers.push(item.id)
    end

    Moment.create!(
      user: current_user,
      name: params[:moment][:name],
      why: params[:moment][:why],
      comment: true,
      viewers: viewers,
      category: params[:moment][:category],
      mood: params[:moment][:mood]
    )

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { render root_path }
    end
  end

  # GET /moments/new
  def new
    @moment = Moment.new
    set_association_variables!
  end

  # GET /moments/1/edit
  def edit
    unless @moment.userid == current_user.id
      redirect_to_path(moment_path(@moment))
    end

    set_association_variables!
  end

  # POST /moments
  # POST /moments.json
  def create
    @moment = Moment.new(moment_params)
    @viewers = current_user.allies_by_status(:accepted)
    @category = Category.new
    @mood = Mood.new
    @strategy = Strategy.new
    respond_to do |format|
      if @moment.save
        format.html { redirect_to moment_path(@moment) }
        format.json { render :show, status: :created, location: @moment }
      else
        format.html { render :new }
        format.json { render json: @moment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moments/1
  # PATCH/PUT /moments/1.json
  def update
    @viewers = current_user.allies_by_status(:accepted)
    @category = Category.new
    @mood = Mood.new
    @strategy = Strategy.new
    respond_to do |format|
      if @moment.update(moment_params)
        format.html { redirect_to moment_path(@moment) }
        format.json { render :show, status: :ok, location: @moment }
      else
        format.html { render :edit }
        format.json { render json: @moment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moments/1
  # DELETE /moments/1.json
  def destroy
    @moment.destroy
    redirect_to_path(moments_path)
  end

  private

  def set_moment
    @moment = Moment.friendly.find(params[:id])
  rescue
    redirect_to_path(moments_path)
  end

  def moment_params
    params.require(:moment).permit(
      :name, :why, :fix, :userid, :comment,
      category: [], mood: [], viewers: [], strategy: []
    )
  end

  def set_association_variables!
    @viewers = current_user.allies_by_status(:accepted)

    @categories = Category.where(user: current_user).order(created_at: :desc)
    @category = Category.new

    @moods = Mood.where(user: current_user).order(created_at: :desc)
    @mood = Mood.new

    @strategies = associated_strategies
    @strategy = Strategy.new
  end

  def associated_strategies
    # current_user's strategies and all viewable strategies from allies
    strategy_ids = Strategy.where(user: current_user).pluck(:id)

    @viewers.each do |ally|
      Strategy.where(userid: ally.id).each do |strategy|
        strategy_ids << strategy.id if strategy.viewer?(current_user)
      end
    end

    Strategy.where(id: strategy_ids).order(created_at: :desc)
  end

  def get_start_by_period(period, end_date)
    case period
    when 'day'
      end_date - 1.week
    when 'week'
      end_date - 1.month
    when 'month'
      end_date - 1.year
    else
      end_date - 1.week
    end
  end
end

app/views/moments/_form.html.erb
<%= render partial: 'shared/editor_modal' %>

<%= form_for(@moment) do |f| %>
<% if @moment.errors.any? %>
  <div class="error_explanation">
    <%= t('common.form.error_explanation') %>
  </div>
<% end %>

<div class="table">

  <div class="table_cell padding_right vertical_align_top sidebar">

    <div class="sidebar_field" >
      <div class="sidebar_label">
        <%= f.label t('common.title'), for: 'moment_name' %>
        <i class="fa fa-asterisk align_right"></i>
        <div class="clear"></div>
      </div>
      <%= f.text_field :name, :class => "name_field" %>
    </div>

    <%= render partial: '/shared/autocomplete_checkboxes', locals: {
        f: f,
        all_data: @categories,
        this_data: @moment.category,
        data_type: 'category',
        data_type_plural: 'categories'
      } %>

    <%= render partial: '/shared/autocomplete_checkboxes', locals: {
        f: f,
        all_data: @moods,
        this_data: @moment.mood,
        data_type: 'mood',
        data_type_plural: 'moods'
      } %>

    <%= render partial: '/shared/autocomplete_checkboxes', locals: {
        f: f,
        all_data: @strategies,
        this_data: @moment.strategy,
        data_type: 'strategy',
        data_type_plural: 'strategies'
      } %>

    <% if !@viewers.nil? && @viewers.length > 0 %>
    <div class="sidebar_field">
      <div class="sidebar_label expand_toggle" data-toggle="#viewers">
        <a href="#" class="toggle_button">
          <i class="fa fa-caret-down"></i>
        </a>
        <%= f.label t('shared.viewers.plural') %>
        <%= content_tag(:span, '<i class="fa fa-question-circle"></i>'.html_safe, class: 'yes_title smaller_margin_left', title: t('moments.form.viewers_hint')) %>
      </div>
    </div>

    <div id="viewers" class="display_none">
      <div id="viewers_list">
        <label>
          <input type="checkbox" id="viewers_all" />
          <span id="viewers_label"><%= t('common.actions.select_all') %></span>
        </label>

        <% @viewers.each do |item| %>
          <label>
            <%= f.check_box(:viewers, {:multiple => true, :checked => @moment.viewers.include?(item.id)}, item.id, nil) %>
            <%= User.where(id: item.id).first.name %>
          </label>
        <% end %>
      </div>
    </div>
    <% end %>

     <div class="sidebar_field">
      <div class="sidebar_label">
        <%= f.label t('comment.allow_comments') %>
        <%= content_tag(:span, '<i class="fa fa-question-circle"></i>'.html_safe, class: 'yes_title smaller_margin_left', title: t('comment.hint')) %>
        <div class="align_right">
          <%= f.check_box :comment, class: 'no_margin_right' %>
        </div>
      </div>
    </div>
  </div>

  <div class="table_cell vertical_align_top">
    <div class="field">
      <div class="label">
        <%= f.label t('moments.form.why'), for: 'moment_why' %>
        <i class="fa fa-asterisk align_right"></i>
        <div class="clear"></div>
      </div>
      <%= f.cktext_area :why, class: 'no_title special_textarea ckeditor' %>

      <%= render :partial => '/shared/character_count', locals: { data: 'moment_why' } %>
    </div>
    <div class="field">
      <div class="label">
        <%= f.label t('moments.form.fix') %>
      </div>
      <%= f.cktext_area :fix, class: 'no_title special_textarea ckeditor' %>

      <%= render :partial => '/shared/character_count', locals: { data: 'moment_fix' } %>
    </div>
  </div>

</div>

<div class="clear"></div>

<div class="actions align_right no_margin_bottom">
  <%= f.hidden_field :userid, :value => current_user.id %>
  <%= f.submit t('common.actions.submit') %>
</div>

<div class="clear"></div>

<% end %>

<%= render :partial => '/shared/quick_create', locals: { data_type: 'category', data: @category, tag: 'moment' } %>

<%= render :partial => '/shared/quick_create', locals: { data_type: 'mood', data: @mood , tag: 'moment' } %>

<%= render :partial => '/shared/quick_create', locals: { data_type: 'strategy', data: @strategy, tag: 'moment' } %>

app/views/moments/_info.html.erb
<%= ::TimeAgo.created_or_edited(local_assigns[:data]) %>
<% if local_assigns[:data].category.count > 0 %>
  <br>
  <strong>
    <%= t('categories.label', count: local_assigns[:data].category.count) %>
  </strong>
  <% local_assigns[:data].category.each do |item| %>
    <span class="notification_wrapper">
      <span class="tip_notifications_button link_style"><%= Category.where(id: item).first.name %></span><% if local_assigns[:data].category.last != item %><%= ', ' %><% end %>
      <%= render :partial => '/notifications/preview', locals: { data: Category.where(id: item).first, edit: edit_category_path(item) } %>
    </span>
  <% end %>
<% end %>

<% if local_assigns[:data].class.name == 'Moment' && local_assigns[:data].mood.count > 0 %>
  <br>
  <strong>
    <%= t('moods.label', count: local_assigns[:data].mood.count) %>
  </strong>
  <% local_assigns[:data].mood.each do |item| %>
    <span class="notification_wrapper">
      <span class="tip_notifications_button link_style"><%= Mood.where(id: item).first.name %></span><% if local_assigns[:data].mood.last != item %><%= ', ' %><% end %>
      <%= render :partial => '/notifications/preview', locals: { data: Mood.where(id: item).first, edit: edit_mood_path(item) } %>
    </span>
  <% end %>
<% end %>

<% if local_assigns[:data].class.name == 'Moment' && local_assigns[:data].strategy.count > 0 && local_assigns[:show_strategies] %>
  <br>
  <strong>
    <%= t('strategies.label', count: local_assigns[:data].strategy.count) %>
  </strong>
  <% local_assigns[:data].strategy.each do |item| %>
    <span class="notification_wrapper">
      <span class="tip_notifications_button link_style"><%= Strategy.where(id: item).first.name %></span><% if local_assigns[:data].strategy.last != item %><%= ', ' %><% end %>
      <%= render :partial => '/notifications/preview', locals: { data: Strategy.where(id: item).first, edit: edit_strategy_path(item) } %>
    </span>
  <% end %>
<% end %>

<% if local_assigns[:home] %>
  <div class="spacer"></div>
  <% if local_assigns[:data].class.name == 'Moment' %>
  <%= strip_tags(local_assigns[:data].why[0..200]) %>
  <% if local_assigns[:data].why.length >= 200 %>
    <%= t('ellipsis') %>
  <% end %>
  <% elsif local_assigns[:data].class.name == 'Strategy' %>
  <%= strip_tags(local_assigns[:data].description[0..200]) %>
  <% if local_assigns[:data].description.length >= 200 %>
    <%= t('ellipsis') %>
  <% end %>
  <% end %>
<% end %>

<% if local_assigns[:class_name] %>
<br>
<div class="align_right subtle class_name">
<% if local_assigns[:data].class.name == 'Moment' %>
  <%= t('moments.singular') %>
<% elsif local_assigns[:data].class.name == 'Strategy' %>
  <%= t('strategies.singular') %>
<% end %>
</div>
<% end %>

<div class="clear"></div>

app/views/moments/_moment.html.erb
<%= render :partial => '/shared/moments_strategies', locals: { items: @moments, item: moment, data_type: 'moment' } %>

app/views/moments/_quick_moment.html.erb
<%= form_for(local_assigns[:moment], url: quick_moment_moments_path) do |f| %>
  <% if local_assigns[:moment].errors.any? %>
    <div class="error_explanation">
      <%= t('common.form.error_explanation') %>
    </div>
  <% end %>

  <div class="table" id="quick_moment">
    <div class="table_row">
      <div class="table_cell small_padding_right vertical_align_middle">
        <%= f.text_field :name, placeholder: t('common.title'), :required => true %>
        <%= f.text_area :why, placeholder: t('moments.form.what_happened'), :required => true %>
        <div class="quick_moment_disclaimer">
          <%= content_tag(:span, '<i class="fa fa-lock"></i>'.html_safe, class: 'yes_title subtle smaller_margin_right', title: t('moments.quick_moment_disclaimer')) %>
          <%= render :partial => '/shared/character_count', locals: { data: 'moment_why' } %>
        </div>
      </div>

      <div class="table_cell center vertical_align_middle">

        <%= render :partial => '/notifications/categories_moods', locals: { categories: local_assigns[:categories], moods: local_assigns[:moods], f: f } %>

        <div class="clear"></div>

        <% if (!local_assigns[:categories].nil? && local_assigns[:categories].length > 0) || (local_assigns[:moods].nil? && local_assigns[:moods].length > 0) %>
          <div id="toggle_categories_moods">
            <span class="link_style">
              <% if !local_assigns[:categories].nil? && local_assigns[:categories].length > 0 &&
                !local_assigns[:moods].nil? && local_assigns[:moods].length > 0 %>
                <%= t('moments.categories_and_moods') %>
              <% elsif !local_assigns[:categories].nil? && local_assigns[:categories].length > 0 %>
                <%= t('categories.plural') %>
              <% elsif !local_assigns[:moods].nil? && local_assigns[:moods].length > 0 %>
                <%= t('moods.plural') %>
              <% end %>
            </span>
          </div>
          <div class="actions no_margin_bottom">
            <%= f.hidden_field :userid, :value => current_user.id %>
            <%= f.submit t('shared.quick_create.new', name: t('moments.singular')) %>
          </div>
        <% else %>
          <div class="actions no_margin_bottom no_margin_top">
            <%= f.hidden_field :userid, :value => current_user.id %>
            <%= f.submit t('shared.quick_create.new', name: t('moments.singular')) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="spacer"></div>

app/views/moments/edit.html.erb
<% title "#{t('common.actions.edit_instance', instance: @moment.name)}" %>
<%= render 'form' %>

app/views/moments/index.html.erb
<% title t('moments.plural') %>
<% page_new new_moment_path %>

<div class="subtitle">
  <%= t('moments.index.subtitle') %>
</div>

<div class="spacer"></div>

<% if @moments.length > 0 %>
  <%= render :partial => '/search/posts', locals: { data_type: 'moment' } %>

  <div class="stats_divider"></div>

  <div class="hide_on_mobile">
    <%= react_component("ChartControl", props: {
        types: [],
        initialParams: {
            type: 'Moments',
            data: {
                Moments: @react_moments,
            }
        }
    })%>

    <div class="spacer"></div>
 </div>

  <%= render :partial => '/shared/stats', locals: { data_type: 'moment' } %>

  <div id="pages">
    <div class="page">
    <%= render @moments %>
    </div>
  </div>

  <%= paginate @moments %>
<% else %>
<%= raw t('moments.index.instructions', {
    icon: '<i class="fa fa-plus-circle"></i>'
  }) %>

<div class="spacer"></div>

<div id="pages">
  <div class="page">
    <div class="moment no_margin_bottom">
    	<h1 class="moment_name">
          <%= content_tag(:span, '<i class="fa fa-lock"></i>'.html_safe, class: 'yes_title small_margin_right', title: t('comment.control')) %>
          <%= t('moments.index.example_name') %>
      	</h1>

        <strong><%= t('categories.label', count: 1) %></strong> <%= t('moments.index.example_category') %>
        <br><strong><%= t('moods.label', count: 3) %></strong> <%= t('moods.example_moods') %>
    </div>
  </div>
</div>
<% end %>

app/views/moments/new.html.erb
<% title "#{t('moments.new')}" %>
<%= render 'form' %>

app/views/moments/show.html.erb
<% title @moment.name %>
<%= render :partial => '/moments/info', locals: { data: @moment } %>
<% if Rails.configuration.secret_share_enabled && @moment.owned_by?(current_user) %>
  <button class="secret-share-button" onclick="$('#secret-share-area').toggleClass('display_none')">
    <%= t ('moments.secret_share.singular') %>
  </button>
  <div class="<%= @moment.shared? ? '' : 'display_none' %>" id="secret-share-area">
    <%= button_to t('moments.secret_share.create'), secret_shares_path(moment: @moment.id), {class: 'secret-share-button'} %>
    <% if @moment.shared? %>
      <%= button_to t('moments.secret_share.cancel'), secret_share_path(@moment.secret_share_identifier), {method: :delete, class: 'secret-share-button'} %>
    <% end %>
    <% if @moment.secret_share_identifier %>
      <input type=text value="<%= secret_share_url(@moment.secret_share_identifier) %>">
      <form class="secret-share-expire">
        <%= t('moments.secret_share.expires_at') %>:
        <input type="date" name="expire">
        <input type="submit" value="<%= t('common.actions.submit') %>">
      </form>
    <% end %>
    <!-- <%= secret_share_url(@moment.secret_share_identifier) if @moment.secret_share_identifier %> -->
  </div>
<% end %>

<% if !@moment.why.blank? %>
  <p>
    <div class="label"><%= label_tag t('moments.form.why') %></div>
    <%= raw(@moment.why) %>
  </p>
<% end %>

<% if !@moment.fix.blank? %>
  <p>
    <div class="label"><%= label_tag t('moments.form.fix') %></div>
    <%= raw(@moment.fix) %>
  </p>
<% end %>

<% if @moment.strategy.count > 0 %>
  <p>
    <div class="label"><%= label_tag t('moments.show.strategies') %></div>
    <% @moment.strategy.each do |item| %>
        <span class="notification_wrapper">
          <span class="tip_notifications_button link_style"><%= Strategy.where(id: item).first.name %></span><% if @moment.strategy.last != item %><%= ', ' %><% end %>
          <%= render :partial => '/notifications/preview', locals: { data: Strategy.where(id: item).first, edit: edit_strategy_path(item) } %>
        </span>
    <% end %>
  </p>
<% end %>

<%= render :partial => '/shared/viewers_indicator', locals: { data: @moment } %>

<% if @comment.present? %>
  <%= render :partial => '/shared/comments', locals: { data: @moment, comments: @comments, comment: @comment, no_hide_page: @no_hide_page, commentable_type: 'moment' } %>
<% end %>